# Generated by Django 6.0 on 2026-01-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_reportcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcard',
            old_name='date_of_report_card',
            new_name='date_of_report_card_generation',
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_report_card_generation')},
        ),
    ]
