# Generated by Django 6.0 on 2026-01-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_rename_date_of_report_card_reportcard_date_of_report_card_generation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='date_of_report_card_generation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
