# Generated by Django 6.0 on 2026-01-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0009_alter_reportcard_date_of_report_card_generation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcard',
            options={'ordering': ['student_rank']},
        ),
    ]
