# Generated by Django 6.0 on 2026-01-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0010_alter_reportcard_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcard',
            options={},
        ),
    ]
