# Generated by Django 6.0 on 2026-01-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0011_alter_reportcard_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
